---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-alpine

inputs:
- name: artifactory-resource

run:
  path: artifactory-resource/ci/scripts/build.sh
