---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8u131-jdk-alpine

inputs:
- name: artifactory-resource

outputs:
- name: artifactory-resource-build

caches:
- path: m2

run:
  path: artifactory-resource/ci/scripts/build.sh
