---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springci/artifactory-resource-ci-image
    tag: master
inputs:
- name: git-repo
outputs:
- name: built-artifact
caches:
- path: maven
run:
  path: git-repo/ci/scripts/build.sh
