---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springio/artifactory-resource-ci

params:
  RELEASE_VERSION: release-version

inputs:
- name: artifactory-resource

outputs:
- name: generated-artifact
- name: artifactory-resource-updated

caches:
- path: m2

run:
  path: artifactory-resource/ci/scripts/update-version.sh