resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/philwebb/artifactory-resource
    branch: master
    ignore_paths: ["ci/images/*"]
- name: ci-images-git-repo
  type: git
  source:
    uri: https://github.com/philwebb/artifactory-resource
    branch: master
    paths: ["ci/images/*"]
- name: artifactory-resource-ci-image
  type: docker-image
  source:
    repository: springci/artifactory-resource-ci-image
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: master
- name: artifactory-resource-image
  type: docker-image
  source:
    repository: springio/artifactory-resource
    username: ((docker-hub-username))
    password: ((docker-hub-password))
jobs:
- name: build-artifactory-resource-ci-image
  plan:
  - get: ci-images-git-repo
    trigger: true
  - put: artifactory-resource-ci-image
    params:
      build: ci-images-git-repo/ci/images/artifactory-resource-ci-image
- name: build
  plan:
  - get: git-repo
    trigger: true
  - task: build
    file: git-repo/ci/tasks/build.yml
  - put: artifactory-resource-image
    params:
      build: .
      dockerfile: git-repo/Dockerfile
      tag: built-artifact/version
      build_args:
        root: git-repo
        jar:  built-artifact/artifactory-resource.jar
- name: release
  plan:
  - get: git-repo
    passed: [build]
    trigger: false
  - task: release
    file: artifactory-resource/ci/tasks/release.yml
  - put: artifactory-resource-image
    params:
      build: .
      dockerfile: git-repo/Dockerfile
      tag: built-artifact/version
      build_args:
        root: git-repo
        jar:  built-artifact/artifactory-resource.jar
