resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/philwebb/artifactory-resource
    branch: master
    ignore_paths: ["ci/images/*"]
- name: ci-images
  type: git
  source:
    uri: https://github.com/philwebb/artifactory-resource
    branch: master
    paths: ["ci/images/*"]
- name: ci-images-docker-registry
  type: docker-image
  source:
    repository: springci/artifactory-resource-ci-image
    tag: master
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
jobs:
- name: build-artifactory-resource-ci-image
  plan:
  - get: ci-images-git-repo
    trigger: true
  - put: ci-images-docker-registry
    params:
      build: git-docker-resource/ci/dockerfiles/artifactory-resource-ci-image
